{% set name = "sepal-ui" %}
{% set version = "2.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7598cfa78a8bb6b11fa4f8ac0e3b6b04e17ad475cf72a5a411928269e52126f2

build:
  entry_points:
    - module_deploy = sepal_ui.bin.module_deploy:main
    - module_factory = sepal_ui.bin.module_factory:main
    - module_l10n = sepal_ui.bin.module_l10n:main
    - module_theme = sepal_ui.bin.module_theme:main
    - module_venv = sepal_ui.bin.module_venv:main
    - activate_venv = sepal_ui.bin.activate_venv:main
    - sepal_ipyvuetify = sepal_ui.bin.sepal_ipyvuetify:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.8
    - tomli
    - ipykernel
    - ipyvuetify
    - markdown
    - ipyleaflet >=0.14.0
    - earthengine-api
    - colorama
    - pipreqs
    - rioxarray
    - dask-core
    - geopandas
    - matplotlib-base
    - jupyter-server-proxy
    - planet
    - pyarrow
    - localtileserver >=0.7.0
    - pygaul >=0.3.1
    - pygadm >=0.5.0
    - python-box
    - tqdm
    - deprecated >=1.2.14
    - anyascii
    - natsort
    - typing-extensions
    - nest-asyncio

test:
  imports:
    - sepal_ui
  commands:
    - pip check
    - module_deploy --help
    - module_factory --help
    - module_l10n --help
    - module_theme --help
    - module_venv --help
    - activate_venv --help
    - sepal_ipyvuetify --help
  requires:
    - pip

about:
  home: https://github.com/12rambau/sepal_ui
  summary: Wrapper for ipyvuetify widgets to unify the display of voila dashboards in SEPAL platform
  license: MIT
  license_file:
    - LICENSE.txt
    - sepal_ui/templates/map_app/LICENSE
    - sepal_ui/templates/panel_app/LICENSE

extra:
  recipe-maintainers:
    - 12rambau
    - dfguerrerom
