{% set name = "sepal-ui" %}
{% set version = "2.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sepal-ui-{{ version }}.tar.gz
  sha256: 850d8e7311ac606a57eb177569eb6f3e07c41831331a76295928f1ef5430cd7c

build:
  entry_points:
    - module_deploy = sepal_ui.bin.module_deploy:main
    - module_factory = sepal_ui.bin.module_factory:main
    - module_l10n = sepal_ui.bin.module_l10n:main
    - module_theme = sepal_ui.bin.module_theme:main
    - module_venv = sepal_ui.bin.module_venv:main
    - activate_venv = sepal_ui.bin.activate_venv:main
    - sepal_ipyvuetify = sepal_ui.bin.sepal_ipyvuetify:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipyvuetify
    - markdown
    - ipyleaflet >=0.14.0
    - earthengine-api
    - colorama
    - pipreqs
    - rioxarray
    - dask
    - geopandas
    - matplotlib-base
    - jupyter-server-proxy
    - planet ==2.0a6
    - pyarrow
    - python-box
    - tqdm
    - Deprecated
    - Unidecode
    - natsort
    - typing-extensions

test:
  imports:
    - sepal_ui
  commands:
    - pip check
    - module_deploy --help
    - module_factory --help
    - module_l10n --help
    - module_theme --help
    - module_venv --help
    - activate_venv --help
    - sepal_ipyvuetify --help
  requires:
    - pip

about:
  home: https://github.com/12rambau/sepal_ui
  summary: Wrapper for ipyvuetify widgets to unify the display of voila dashboards in SEPAL platform
  license: MIT
  license_file:
    - LICENSE.txt
    - sepal_ui/templates/map_app/LICENSE
    - sepal_ui/templates/panel_app/LICENSE

extra:
  recipe-maintainers:
    - 12rambau
